---
- name: turn off community-grid
  hosts: web
  gather_facts: false
  become: true
  tasks:
    - name: list installed packages
      package_facts:

    - name: print installed packages
      debug:
        var: ansible_facts.packages

    - name: disable and stop boinc-client
      systemd:
        name: boinc-client
        state: stopped
        enabled: false
      when: '"boinc-client" in ansible_facts.packages'
